---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
platforms:
- name: ubuntu-14.04
suites:
- name: default
  run_list:
  - recipe[ubuntu-workstation::default]
  - recipe[ubuntu-workstation::default_editor]
  - recipe[ubuntu-workstation::gina-sub]
  - recipe[ubuntu-workstation::git]
  - recipe[ubuntu-workstation::moreutils]
  - recipe[ubuntu-workstation::tmux]
  - recipe[ubuntu-workstation::user_profile]
  - recipe[ubuntu-workstation::vim]
  - recipe[ubuntu-workstation::feh]
  - recipe[ubuntu-workstation::samba]
  - recipe[ubuntu-workstation::cinnamon-desktop]
  attributes:
    workstation_user: vagrant
    users:
    - test
    samba:
      users:
      - name: test
        plaintextpassword: testsambapassword
      shares:
        root:
          comment: Workstation root Directory
          path: /
          guest ok: false
          printable: false
          write list:
          - test
          read only: false
